<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="FIS-100" ignored="0" name="Test" tests="2" failures="1" timestamp="02 Mar 2018 09:10:47 GMT" time="0.093" errors="0">
  <testcase name="Dummy_test_fail" time="0.016" classname="testmave1.TC02">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]at testmave1.TC02.Dummy_test_fail(TC02.java:14)... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Dummy_test_fail -->
  <testcase name="Dummy_test_pass" time="0.0" classname="testmave1.TC02"/>
</testsuite> <!-- Test -->
